name: Automerge Release-Please PRs

on:
  schedule:
    - cron: '21 1 * * 6' # runs every Saturday at 01:21 UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: 1027247 # kellervater-release-please
          private-key: ${{ secrets.RELEASE_PLEASE_SECRET_KEY }}
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          # we're using squash as merge method to allow a requirement for signed commits on the base branch
          script: |
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'autorelease: pending',
            });
            const pullRequests = issues.data.filter(issue => issue.pull_request);
            for (const pr of pullRequests) {
              await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
              merge_method: 'squash',
              });
            }
