name: Automerge Release-Please PRs

on:
  schedule:
    - cron: '36 4 * * 1' # runs every Monday at 04:36 UTC
  workflow_dispatch: # so we can run it on non-mainline branches

permissions:
  contents: write       # so we can modify the changelog
  pull-requests: write  # so release-please can create/update PRs
  actions: write        # so subsequent actions can run

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      # - name: Create Release
      #   uses: camunda/infra-global-github-actions/teams/infra/pull-request/automerge@infra-gh-614-automerge
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: automerge
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: "squash"
          MERGE_LABELS: "automerge"
          LOG: "DEBUG"