name: Automerge Release-Please PRs

on:
  schedule:
    - cron: '0 4 * * 6'  # Runs every Saturday at 4 AM CET
  workflow_dispatch:  # Allows manual triggering

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: 1027247 # kellervater-release-please
          private-key: ${{ secrets.RELEASE_PLEASE_SECRET_KEY }}
      - uses: actions/checkout@v2
      - uses: actions/github-script@v3
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          # we're using squash as merge method to allow the requirement for signed commits on the base branch
          script: |
            const { data: issues } = await github.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'autorelease: pending',
            });
            const pullRequests = issues.filter(issue => issue.pull_request);
            for (const pr of pullRequests) {
              await github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
              merge_method: 'squash',
              });
            }
