name: Automerge Release-Please PRs

on:
  schedule:
    - cron: '*/5 * * * *' # runs every 5 minutes

permissions:
  contents: write       # so we can modify the changelog
  pull-requests: write  # so release-please can create/update PRs
  actions: write        # so subsequent actions can run

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: camunda/infra-global-github-actions/teams/infra/pull-request/automerge@infra-gh-614-automerge
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
