name: Automerge Release-Please PRs

on:
  schedule:
    - cron: '*/5 * * * *' # runs every 5 minutes

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: 1027247 # kellervater-release-please
          private-key: ${{ secrets.RELEASE_PLEASE_SECRET_KEY }}
      - name: Create Release
        uses: camunda/infra-global-github-actions/teams/infra/pull-request/automerge@infra-gh-614-automerge
        with:
          github-token: ${{ steps.app-token.outputs.token }}
