---
  name: monorepo permutations
  
  on:
    push:
      tags:
      - '*.*v*.*.*'
  
  env:
    IMAGE_NAME: ci-30-162810/main/mysql
  
  jobs:
    matrix_prep:
      runs-on: ubuntu-24.04
      outputs:
        matrix: ${{ steps.set-matrix.outputs.matrix }}
      steps:
        - uses: actions/checkout@v4
        - name: set-matrix
          id: set-matrix
          run: |
            if [[ ${{github.ref}} =~ 'refs/tags/' ]]
            then
              TAG=${GITHUB_REF/refs\/tags\//}
              VERSION=${TAG%%v*}
              if [[ $VERSION == "5.x" ]]
              then
                echo "matrix={\"include\":[{\"VERSION\":\"5.6\"},{\"VERSION\":\"5.7\"}]}" >> "$GITHUB_OUTPUT"
              else
                echo "matrix={\"VERSION\":[\"$VERSION\"]}" >> "$GITHUB_OUTPUT"
              fi
            fi
  
    docker:
      needs: matrix_prep
      strategy:
        matrix: ${{fromJson(needs.matrix_prep.outputs.matrix)}}
      runs-on: ubuntu-24.04
  
      steps:
      - uses: actions/checkout@v4

      - id: test_new_images
        shell: bash
        if: ${{ matrix.VERSION >= 8.0 }}
        run: |
          echo "would build image for version >= 8.0 (${{ matrix.VERSION }})"
  
      - id: test_old_images
        shell: bash
        if: ${{ matrix.VERSION < 8.0 }}
        run: |
          echo "would build image for version < 8.0 (${{ matrix.VERSION }})"
  