on:
  push:
    branches:
      - main
  workflow_dispatch:

name: Update Release PR

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: 1027247 # kellervater-release-please
          private-key: ${{ secrets.RELEASE_PLEASE_SECRET_KEY }}
      - uses: camunda/infra-global-github-actions/teams/infra/pull-request/release@main
        with:
          github-token: ${{ steps.app-token.outputs.token }}
