on:
  push:
    branches:
      - main

name: Upsert Release PR

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: 1027247 # kellervater-release-please
          private-key: ${{ secrets.RELEASE_PLEASE_SECRET_KEY }}
      - uses: googleapis/release-please-action@v4
        with:
          config-file: .github/config/release-please-config.yml
          manifest-file: .github/config/release-please-manifest.yml
          token: ${{ steps.app-token.outputs.token }}
