name: Mirror Dependency Version

on:
  push:
    branches:
      - 'renovate/*'
    paths:
      - 'Dockerfile'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: 1027247 # kellervater-release-please
          private-key: ${{ secrets.RELEASE_PLEASE_SECRET_KEY }}        
      - name: Run script
        shell: bash
        run: |
          version=$(awk '/^FROM ghcr.io\/actions\/actions-runner/ {split($2, a, ":"); print a[2]}' Dockerfile)
          git commit --allow-empty -m "Release-As: $version"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/${{ github.repository }}.git
          git push origin HEAD
