on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: Update Release PR

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: camunda/infra-global-github-actions/pull-request/release-please@infra-gh-614-automerge
        with:
          manifest-filename: .github/config/.release-please-manifest.json
          github-token: ${{ secrets.GITHUB_TOKEN}}
